export default interface IConfig {
    id: string,
    banner1: string,
    banner2: string,
    banner3: string,
    bannerLink1: string,
    bannerLink2: string,
    bannerLink3: string,
    categorie1: string,
    categorie2: string,
    categorie3: string,
    categorieImageLink1: string,
    categorieImageLink2: string,
    categorieImageLink3: string,
    categorieImageLink4: string,
    categorieImageLink5: string, 
    categorieImage1: string,
    categorieImage2: string,
    categorieImage3: string,
    categorieImage4: string,
    categorieImage5: string, 
}